### ISSUE TITLE
About  the function Zout_K2

### ISSUE THREAD

**Issue by cheng18175030250** [benjaminaubin/TheCommitteeMachine#1]
@benjaminaubin  Thanks for your sharing. And it helps me a lot! Could you explain the function of Zout_K2 in gout_sign_sign.py. I'm very curious how does it implement Zout's formula in the article. In particular, the decomposition of V , the meaning of omega_tilde and the meaning of lower ,upper limit of integration bother me for a long time.

**Comment by benjaminaubin** [comment]
Dear @cheng18175030250, 

The Zout_K2 method computes the integral Z_Pout(\omega, y, V) in [page 39](https://arxiv.org/pdf/1806.05451.pdf). From it we can obtain the gout(\omega, y, V) and dgout_domega(\omega, y, V) used in the AMP algorithm. 

The main difficulty is to compute the Z_Pout K-dimensional integral. In the case of a sign-sign committee machine for K=2, the integral can be composed in three simple domains depending on the values of the output y={+1, -1, 0}
- z1>0 and z2>0
- z1<0 and z2<0 
- z1>0 and z2<0 or  z1<0 and z2>0 
that correspond to the code in line 89, 93, 97.

The computation for K=2 has been done simply by reformulating the 2d multivariate Gaussian to the 1D Gaussian integration of a Erf function, by simply separating integration over z1 and z2. 

V is a matrix of size 2 x 2 for K=2, and only V_inv is involved and defined as V^{-1} := [[a , c], [c, b]] (because it is symmetric)

Omega_tilde correponds to upper/lower bounds of the integrals after the change of variables. For clarity I share my notes with you that correspond to the implementation: 
[Committee_machines pages 28 - 30.pdf](https://github.com/benjaminaubin/TheCommitteeMachine/files/5824671/Committee_machines.pages.28.-.30.pdf)

I hope this will help you.

**Comment by cheng18175030250** [comment]
Dear @benjaminaubin ，

😀Thanks for your reply and notes. When solving for Zout and dZout, the notes say "Using 7.2.1" and "Using 7.2.2", but I couldn't get it. If possible, could you please share the content of those two sections with me. Sorry to bother you again.

**Comment by benjaminaubin** [comment]
Yes, I did not add section 7.2 because it was badly referenced. In fact, the computation was still on my handwritten notes. To clarify the missing steps I wrote a quick note for the term Zout^+:
[zout+.pdf](https://github.com/benjaminaubin/TheCommitteeMachine/files/5831268/zout%2B.pdf)
 
 The computation is very similar for the other terms and derivatives.
Best

**Comment by cheng18175030250** [comment]
@benjaminaubin  Thank you so much for your assistance. Best wishes!
